name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/workflow-test.yml
    permissions:
      contents: read

  done:
    name: Done
    needs:
      - validate
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Fail If Any Job Did Not Succeed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
